const STORE_KEY = 'AUTH'

export const FETCH_AUTH_LOADING_REQUEST = `${STORE_KEY}/FETCH_AUTH_LOADING_REQUEST`
export const FETCH_AUTH_LOADING_SUCCESS = `${STORE_KEY}/FETCH_AUTH_LOADING_SUCCESS`
export const FETCH_AUTH_LOADING_FAILURE = `${STORE_KEY}/FETCH_AUTH_LOADING_FAILURE`

export const FETCH_AUTH_STATUS_REQUEST = `${STORE_KEY}/FETCH_AUTH_STATUS_REQUEST`
export const FETCH_AUTH_STATUS_SUCCESS = `${STORE_KEY}/FETCH_AUTH_STATUS_SUCCESS`
export const FETCH_AUTH_STATUS_FAILURE = `${STORE_KEY}/FETCH_AUTH_STATUS_FAILURE`

export const FETCH_AUTH_USER_SUCCESS = `${STORE_KEY}/FETCH_AUTH_USER_SUCCESS`
export const FETCH_AUTH_USER_FAILURE = `${STORE_KEY}/FETCH_AUTH_USER_FAILURE`
